export const LANGUAGES = {
  en: {
    code: "en",
    name: "English",
    native: "English",
    flag: "🇬🇧",
    speech_recognition_code: "en-IN",
    speech_synthesis_lang: "en-IN",
    placeholder: "Describe your symptoms... (e.g. I have chest pain and fever)",
    greeting: "Hello! I'm VaidyaAI. Tell me what symptoms you're experiencing and I'll help guide you.",
    emergency_text: "Call 108 NOW!",
    loading_text: "Analyzing your symptoms...",
  },
  te: {
    code: "te",
    name: "Telugu",
    native: "తెలుగు",
    flag: "🇮🇳",
    speech_recognition_code: "te-IN",
    speech_synthesis_lang: "te-IN",
    placeholder: "మీ లక్షణాలు వివరించండి... (ఉదా: నాకు ఛాతీ నొప్పి మరియు జ్వరం వస్తుంది)",
    greeting: "నమస్కారం! నేను VaidyaAI. మీకు ఏ లక్షణాలు వస్తున్నాయో చెప్పండి, నేను మీకు మార్గనిర్దేశం చేస్తాను.",
    emergency_text: "ఇప్పుడే 108కి కాల్ చేయండి!",
    loading_text: "మీ లక్షణాలు విశ్లేషిస్తున్నాం...",
  },
  hi: {
    code: "hi",
    name: "Hindi",
    native: "हिंदी",
    flag: "🇮🇳",
    speech_recognition_code: "hi-IN",
    speech_synthesis_lang: "hi-IN",
    placeholder: "अपने लक्षण बताएं... (जैसे: मुझे सीने में दर्द और बुखार है)",
    greeting: "नमस्ते! मैं VaidyaAI हूँ। आपको कौन से लक्षण हो रहे हैं, बताएं — मैं आपकी मदद करूँगा।",
    emergency_text: "अभी 108 पर कॉल करें!",
    loading_text: "आपके लक्षणों का विश्लेषण हो रहा है...",
  },
  ta: {
    code: "ta",
    name: "Tamil",
    native: "தமிழ்",
    flag: "🇮🇳",
    speech_recognition_code: "ta-IN",
    speech_synthesis_lang: "ta-IN",
    placeholder: "உங்கள் அறிகுறிகளை விவரிக்கவும்... (எ.கா: என் மார்பில் வலி மற்றும் காய்ச்சல் உள்ளது)",
    greeting: "வணக்கம்! நான் VaidyaAI. உங்களுக்கு என்ன அறிகுறிகள் உள்ளன என்று சொல்லுங்கள், நான் உங்களுக்கு வழிகாட்டுவேன்.",
    emergency_text: "இப்போதே 108 ஐ அழைக்கவும்!",
    loading_text: "உங்கள் அறிகுறிகளை பகுப்பாய்வு செய்கிறோம்...",
  },
}

export const getLanguage = (code) => LANGUAGES[code] || LANGUAGES.en
