// Form labels and placeholder text for ASHA Mode in all 4 languages
export const ASHA_FORM_LABELS = {
  en: {
    title: 'Village Visit Session',
    villagePlaceholder: 'Enter village name...',
    patientOf: 'Patient',
    ofToday: "of today's visit",
    endSession: 'End Session & Export',
    sectionPatient: 'Patient Details',
    labelAge: 'Age (years)',
    labelAgeGroup: 'Age Group',
    labelGender: 'Gender',
    labelComplaint: 'Chief Complaint',
    complaintPlaceholder: 'Describe the main problem in the patient\'s own words...',
    labelDuration: 'Duration',
    labelFever: 'Fever?',
    labelTemp: 'Temperature (°F)',
    labelBreathing: 'Breathing Difficulty',
    labelConsciousness: 'Consciousness',
    labelPregnancy: 'Pregnancy',
    labelPhoto: 'Symptom Photo',
    btnDecision: 'Get AI Triage Decision',
    btnLog: 'Log This Patient',
    btnNext: 'Next Patient',
    ageGroups: ['Infant <1yr', 'Child 1–12', 'Adult 13–59', 'Elderly 60+'],
    genders: ['Male', 'Female', 'Other'],
    durations: ['1 day', '2–3 days', '4–7 days', '7+ days'],
    breathings: ['None', 'Mild', 'Severe'],
    consciousnesses: ['Alert', 'Confused', 'Unconscious'],
    pregnancies: ['Yes', 'No', 'N/A'],
    fromKit: 'From Your Kit',
    referTo: 'Refer To',
    tellFamily: 'Tell the Family',
    redFlags: 'Watch For',
    followUp: 'Follow-up',
    followUpDays: 'days',
    reasoning: 'Clinical Reasoning',
    patientsLogged: 'Patients Logged This Session',
    exportReport: 'Export Report (WhatsApp)',
    noPatients: 'No patients logged yet.',
    emergencyCall: 'CALL 108 NOW',
    confidence: 'Confidence',
  },
  te: {
    title: 'గ్రామ పర్యటన సెషన్',
    villagePlaceholder: 'గ్రామం పేరు నమోదు చేయండి...',
    patientOf: 'రోగి',
    ofToday: 'ఈరోజు పర్యటనలో',
    endSession: 'సెషన్ ముగించి నివేదిక ఎగుమతి చేయండి',
    sectionPatient: 'రోగి వివరాలు',
    labelAge: 'వయస్సు (సంవత్సరాలు)',
    labelAgeGroup: 'వయస్సు సమూహం',
    labelGender: 'లింగం',
    labelComplaint: 'ప్రధాన సమస్య',
    complaintPlaceholder: 'రోగి చెప్పిన మాటలలో ప్రధాన సమస్య వివరించండి...',
    labelDuration: 'వ్యవధి',
    labelFever: 'జ్వరం?',
    labelTemp: 'ఉష్ణోగ్రత (°F)',
    labelBreathing: 'శ్వాస సమస్య',
    labelConsciousness: 'స్పృహ స్థితి',
    labelPregnancy: 'గర్భం',
    labelPhoto: 'లక్షణ ఫోటో',
    btnDecision: 'AI ట్రియాజ్ నిర్ణయం తీసుకోండి',
    btnLog: 'ఈ రోగిని లాగ్ చేయండి',
    btnNext: 'తదుపరి రోగి',
    ageGroups: ['శిశువు <1 సంవత్సరం', 'బాలుడు 1–12', 'వయోజనుడు 13–59', 'వృద్ధుడు 60+'],
    genders: ['పురుషుడు', 'స్త్రీ', 'ఇతర'],
    durations: ['1 రోజు', '2–3 రోజులు', '4–7 రోజులు', '7+ రోజులు'],
    breathings: ['లేదు', 'తేలికపాటి', 'తీవ్రమైన'],
    consciousnesses: ['మెలకువలో', 'గందరగోళంగా', 'స్పృహలేని'],
    pregnancies: ['అవుని', 'కాదు', 'వర్తించదు'],
    fromKit: 'మీ కిట్ నుండి',
    referTo: 'రెఫర్ చేయండి',
    tellFamily: 'కుటుంబానికి చెప్పండి',
    redFlags: 'జాగ్రత్తగా గమనించండి',
    followUp: 'ఫాలో-అప్',
    followUpDays: 'రోజులు',
    reasoning: 'క్లినికల్ వివరణ',
    patientsLogged: 'ఈ సెషన్లో లాగ్ అయిన రోగులు',
    exportReport: 'నివేదిక ఎగుమతి (WhatsApp)',
    noPatients: 'ఇంకా రోగులు లాగ్ కాలేదు.',
    emergencyCall: 'ఇప్పుడే 108కి కాల్ చేయండి',
    confidence: 'నమ్మకం',
  },
  hi: {
    title: 'ग्राम दौरा सत्र',
    villagePlaceholder: 'गाँव का नाम दर्ज करें...',
    patientOf: 'मरीज़',
    ofToday: 'आज के दौरे में',
    endSession: 'सत्र समाप्त करें और रिपोर्ट निर्यात करें',
    sectionPatient: 'मरीज़ का विवरण',
    labelAge: 'उम्र (वर्ष)',
    labelAgeGroup: 'उम्र समूह',
    labelGender: 'लिंग',
    labelComplaint: 'मुख्य शिकायत',
    complaintPlaceholder: 'मरीज़ के अपने शब्दों में मुख्य समस्या बताएं...',
    labelDuration: 'अवधि',
    labelFever: 'बुखार?',
    labelTemp: 'तापमान (°F)',
    labelBreathing: 'सांस लेने में कठिनाई',
    labelConsciousness: 'चेतना',
    labelPregnancy: 'गर्भावस्था',
    labelPhoto: 'लक्षण की फोटो',
    btnDecision: 'AI ट्राइएज निर्णय प्राप्त करें',
    btnLog: 'इस मरीज़ को लॉग करें',
    btnNext: 'अगला मरीज़',
    ageGroups: ['शिशु <1 वर्ष', 'बच्चा 1–12', 'वयस्क 13–59', 'बुजुर्ग 60+'],
    genders: ['पुरुष', 'महिला', 'अन्य'],
    durations: ['1 दिन', '2–3 दिन', '4–7 दिन', '7+ दिन'],
    breathings: ['कोई नहीं', 'हल्का', 'गंभीर'],
    consciousnesses: ['सतर्क', 'भ्रमित', 'बेहोश'],
    pregnancies: ['हाँ', 'नहीं', 'लागू नहीं'],
    fromKit: 'आपकी किट से',
    referTo: 'रेफर करें',
    tellFamily: 'परिवार को बताएं',
    redFlags: 'इन पर ध्यान दें',
    followUp: 'फॉलो-अप',
    followUpDays: 'दिन',
    reasoning: 'नैदानिक तर्क',
    patientsLogged: 'इस सत्र में लॉग किए गए मरीज़',
    exportReport: 'रिपोर्ट निर्यात करें (WhatsApp)',
    noPatients: 'अभी तक कोई मरीज़ लॉग नहीं हुआ।',
    emergencyCall: 'अभी 108 पर कॉल करें',
    confidence: 'विश्वास',
  },
  ta: {
    title: 'கிராம வருகை அமர்வு',
    villagePlaceholder: 'கிராமத்தின் பெயரை உள்ளிடவும்...',
    patientOf: 'நோயாளி',
    ofToday: 'இன்றைய வருகையில்',
    endSession: 'அமர்வை முடித்து அறிக்கையை ஏற்றுமதி செய்',
    sectionPatient: 'நோயாளி விவரங்கள்',
    labelAge: 'வயது (ஆண்டுகள்)',
    labelAgeGroup: 'வயது குழு',
    labelGender: 'பாலினம்',
    labelComplaint: 'முக்கிய புகார்',
    complaintPlaceholder: 'நோயாளியின் சொந்த வார்த்தைகளில் முக்கிய சிக்கலை விவரிக்கவும்...',
    labelDuration: 'கால அளவு',
    labelFever: 'காய்ச்சலா?',
    labelTemp: 'வெப்பநிலை (°F)',
    labelBreathing: 'சுவாச சிரமம்',
    labelConsciousness: 'நனவு நிலை',
    labelPregnancy: 'கர்ப்பம்',
    labelPhoto: 'அறிகுறி புகைப்படம்',
    btnDecision: 'AI Triage முடிவு பெறவும்',
    btnLog: 'இந்த நோயாளியை பதிவு செய்',
    btnNext: 'அடுத்த நோயாளி',
    ageGroups: ['குழந்தை <1 வருடம்', 'சிறுவர் 1–12', 'வயது முதிர்ந்த 13–59', 'முதியோர் 60+'],
    genders: ['ஆண்', 'பெண்', 'மற்றவர்'],
    durations: ['1 நாள்', '2–3 நாட்கள்', '4–7 நாட்கள்', '7+ நாட்கள்'],
    breathings: ['எதுவும் இல்லை', 'லேசான', 'கடுமையான'],
    consciousnesses: ['விழிப்பான', 'குழப்பமான', 'மயக்கமான'],
    pregnancies: ['ஆம்', 'இல்லை', 'பொருந்தாது'],
    fromKit: 'உங்கள் கிட்டில் இருந்து',
    referTo: 'பரிந்துரைக்கவும்',
    tellFamily: 'குடும்பத்திடம் சொல்லுங்கள்',
    redFlags: 'கவனிக்க வேண்டியவை',
    followUp: 'தொடர்-கண்காணிப்பு',
    followUpDays: 'நாட்கள்',
    reasoning: 'மருத்துவ தர்க்கம்',
    patientsLogged: 'இந்த அமர்வில் பதிவான நோயாளிகள்',
    exportReport: 'அறிக்கையை ஏற்றுமதி (WhatsApp)',
    noPatients: 'இன்னும் நோயாளிகள் பதிவு ஆகவில்லை.',
    emergencyCall: 'இப்போதே 108 ஐ அழைக்கவும்',
    confidence: 'நம்பகத்தன்மை',
  },
}

export const getASHALabels = (lang) => ASHA_FORM_LABELS[lang] || ASHA_FORM_LABELS.en
